AccountData: {
  shape: class

	bio_links: Vec<String>
	bio: String
	current_avatar_image_url: Url
	current_avatar_tags: Vec<serde_json::Value>
	current_avatar_thumbnail_image_url: Url
	developer_type: DeveloperType
	display_name: String
	id: id::User
	is_friend: bool
	last_platform: PlatformType
	profile_pic_override: Option<Url>
	status_description: String
	status: UserStatus
	tags: Vec<String>
	user_icon: Option<Url>
}

UserOrFriendData: {
	shape: class

	location: OfflineOrPrivateOr<id::Instance>
}


StatusData: {
	shape: class

	last_activity: OffsetDateTime
	state: UserState
}

FriendUserStatusData: {
	shape: class

	traveling_to_instance: OfflineOrPrivateOr<id::Instance>
	traveling_to_location: String
	traveling_to_world: OfflineOrPrivateOr<id::World>
}
FriendUserStatusData -> StatusData

FriendData: {
  shape: class

  friend_key: String
  last_login: OffsetDateTime
}

Friend: {
  shape: class

	#fallback_avatar: id::Avatar
	image_url: Url
}
Friend -> AccountData
Friend -> FriendData
Friend -> UserOrFriendData

PastDisplayName: {
  shape: class

  display_name: String
  reverted: Option<bool>
  updated_at: OffsetDateTime
}

CurrentAccountData: {
  shape: class

	accepted_privacy_version: u8
	account_deletion_date: serde_json::Value
	account_deletion_log: serde_json::Value
	current_avatar_asset_url: Url
	email_verified: bool
	fallback_avatar: id::Avatar
	friend_group_names: Vec<serde_json::Value>
	friends: Vec<id::User>
	google_id: String
	has_birthday: bool
	has_email: bool
	has_logged_in_from_client: bool
	has_pending_email: bool
	home_location: Option<id::World>
	obfuscated_email: String
	obfuscated_pending_email: String
	oculus_id: String
	oculus_id: String
	past_display_names: Vec<PastDisplayName>
	pico_id: String
	status_first_time: bool
	status_history: Vec<String>
	steam_details: serde_json::Value
	steam_id: String
	two_factor_auth_enabled_date: Option<OffsetDateTime>
	two_factor_auth_enabled: bool
	unsubscribe: bool
	username: String
	vive_id: String
  accepted_tos_version: u8
}
CurrentAccountData -- PastDisplayName: "past_display_names" {
	source-arrowhead.label: 1
	target-arrowhead.label: *
}

Presence: {
  shape: class

	current_avatar_tags: Vec<serde_json::Value>
	is_rejoining: serde_json::Value
	traveling_to_instance: id::OfflineOrPrivateOr<id::Instance>
	traveling_to_world: id::OfflineOrPrivateOr<id::World>
	world: id::OfflineOr<String>
  avatar_thumbnail: Option<Url>
  display_name: String
  groups: Vec<serde_json::Value>
  id: id::User
  instance_type: String
  instance: id::OfflineOr<id::Instance>
  platform: PlatformType
  profile_pic_override: Option<Url>
  status: UserStatus
  user_icon: Option<Url>
}

CurrentAccount: {
  shape: class

	active_friends: Vec<id::User>
	current_avatar: String
	online_friends: Vec<id::User>
	updated_at: OffsetDateTime
  offline_friends: Vec<id::User>
  presence: Presence
}
CurrentAccount -> AccountData
CurrentAccount -> FriendData
CurrentAccount -> CurrentAccountData
CurrentAccount -> StatusData
CurrentAccount -- Presence: "presence" {
	source-arrowhead.label: 1
	target-arrowhead.label: 1
}


endpoint_friends: Friends endpoint
endpoint_friends.shape: cloud
endpoint_friends -> Friend {
	source-arrowhead.label: 1
	target-arrowhead.label: *
}

endpoint_current_user: Current user endpoint
endpoint_current_user.shape: cloud
endpoint_current_user -- CurrentAccount {
	source-arrowhead.label: 1
	target-arrowhead.label: 1
}

User: {
  shape: class
  
	instance_id: OfflineOrPrivateOr<id::Instance>
	note: String
	world_id: OfflineOrPrivateOr<id::World>
  allow_avatar_copying: bool
  date_joined: Date
  friend_request_status: FriendRequestStatus
}
User -> AccountData
User -> UserOrFriendData


FriendUser: {
  shape: class
}
FriendUser -> User
FriendUser -> FriendData
FriendUser -> FriendUserStatusData

CurrentUser: {
  shape: class
}
CurrentUser -> User
CurrentUser -> FriendData
CurrentUser -> CurrentAccountData
CurrentUser -> FriendUserStatusData

endpoint_users: Users endpoint
endpoint_users.shape: cloud
endpoint_users -- User {
	source-arrowhead.label: 1
	target-arrowhead.label: *
}
endpoint_users -- FriendUser {
	source-arrowhead.label: 1
	target-arrowhead.label: *
}
endpoint_users -- CurrentUser {
	source-arrowhead.label: 1
	target-arrowhead.label: *
}
